FROM golang:1.16-buster AS build

WORKDIR /app

COPY go.mod ./
COPY . ./

RUN go build -o /devops_test

##
## Deploy
##
FROM gcr.io/distroless/base-debian10

WORKDIR /

COPY --from=build /devops_test /devops_test_multi
COPY . ./

EXPOSE 8080

USER nonroot:nonroot

ENTRYPOINT ["/devops_test_multi"]